import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class", "selector"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#2E7D32",
          foreground: "#FFFFFF",
          900: "#112F13",
          800: "#1C4D1F",
          700: "#2E7D32",
          600: "#75CC79",
          500: "#9FDBA2",
          400: "#C2E8C4",
          300: "#DCF2DE",
          200: "#F0F9F0",
          100: "#FBFEFB",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          900: "#492400",
          800: "#894500",
          700: "#FF9934",
          600: "#FFB46A",
          500: "#FFCB97",
          400: "#FFDEBD",
          300: "#FFECDA",
          200: "#FFF7EE",
          100: "#FFFDFB",
        },
        text: {
          DEFAULT: "#857878",
          900: "#473D3D",
          800: "#5C5050",
          700: "#706464",
          600: "#857878",
          500: "#998D8D",
          400: "#ADA2A2",
          300: "#C2B8B8",
          200: "#D6CFCF",
          100: "#EBE7E7",
        },
        info: {
          DEFAULT: "#1976D2",
          900: "#00254A",
          800: "#00254A",
          700: "#00478E",
          600: "#0A5DB0",
          500: "#1976D2",
          400: "#2D91F4",
          300: "#5EAFFF",
          200: "#8CC6FF",
          100: "#BBDDFF",
        },
        success: {
          DEFAULT: "#388E3C",
          900: "#164A18",
          800: "#256C28",
          700: "#388E3C",
          600: "#4FB053",
          500: "#69D26E",
          400: "#86F48B",
          300: "#A5FEAA",
          200: "#C0FFC3",
          100: "#D9FFDB",
        },
        warning: {
          DEFAULT: "#FFB73C",
          100: "#FFF9EF",
          200: "#FFF2DB",
          300: "#FFE8BF",
          400: "#FFDA9B",
          500: "#FFCA70",
          600: "#FFB73C",
          700: "#FFA100",
          800: "#8E5A00",
          900: "#4A2F00",
        },
        error: {
          DEFAULT: "#DE6161",
          100: "#FCF2F2",
          200: "#F9E2E2",
          300: "#F4CBCB",
          400: "#EEAEAE",
          500: "#E68B8B",
          600: "#DE6161",
          700: "#D33131",
          800: "#771919",
          900: "#3D0D0D",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
